---
# Run the deploy_vmare playbook against the control host

- name: Deploy the new vm from VCenter.
  hosts: deploy
  gather_facts: false
  vars_files:
    - vmware-deploy/vars/vault

  vars_prompt:
    - name: "vsphere_user"
      prompt: "VSphere user"
      private: no
    - name: "vsphere_password"
      prompt: "vSphere Password"
      private: yes
    - name: "esxi_host"
      prompt: "ESXi host"
      private: no
      default: atlantis.plumbus.lab
    - name: "notes"
      prompt: "VM notes"
      private: no
      default: "Deployed with ansible"
  roles:
     - vmware-deploy

- name: Join new hosts to the domain.
  hosts: deploy
  become: true
  roles:
    - krb5_user