---
# Run the deploy_vmare playbook against the control host

- hosts: deploy
  gather_facts: false

  vars_prompt:
    - name: "vsphere_user"
      prompt: "VSphere user"
      private: no
      default: smiledt@plumbus.lab
    - name: "vsphere_password"
      prompt: "vSphere Password"
      private: yes
    - name: "esxi_host"
      prompt: "ESXi host"
      private: no
      default: atlantis.plumbus.lab
    - name: "notes"
      prompt: "VM notes"
      private: no
      default: "Deployed with ansible"
  roles:
     - vmware_deploy

# - name: Wait for 120 seconds port 22 to come online.
#   hosts: localhost
#   tasks:
#     - name: Pause for 2 minutes.
#       pause:
#         minutes: 2

# - name: Wait for port 22 to come online for the new vms.
#   hosts: deploy
#   gather_facts: false
#   tasks:
#     - name: Wait for port 22.
#       wait_for_connection:
#         delay: 60
#         timeout: 600
#       delegate_to: localhost

# Do not assume the inventory_hostname is resolvable and delay 10 seconds at start
# - name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
#   hosts: localhost
#   gather_facts: false
#   tasks:
#     - name: Wait for port 22 on the new servers. 
#       wait_for:
#         host: 192.168.1.31
#         port: 22
#         delay: 10
        

- name: Add the ansible management user.
  hosts: deploy
  gather_facts: false
  remote_user: "{{ provisioned_user_name }}"
  become: true
  vars_files:
    - management_user/vars/vault
  vars:
    ansible_become_pass: "{{ provisioned_user_pass }}"
    ansible_ssh_pass: "{{ provisioned_user_pass }}"
  roles:
    - role: management_user

- name: Add the standard user account.
  hosts: deploy
  become: true
  roles:
    - role: standard_user

- name: Join new hosts to the domain.
  hosts: deploy
  become: true
  roles:
    - krb5_user
