---
- name: Converge
  hosts: all
  vars_files: 
    - ../../management_user/defaults/main.yml
    - ../../standard_user/defaults/main.yml
  tasks:
    - name: Update apt cache (on Debian)
      apt: 
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

    - name: Install dependencies
      pip:
        name: passlib
        state: present

    - name: "Test the management user role."
      include_role:
        name: "management_user"
      vars:
        ansible_become_pass: "molecule_testing"
        ansible_ssh_pass: "molecule_testing"
        vault_management_pass: "molecule_testing"

    - name: "Ensure the user {{ standard_user }} exists (this user exists by default in my environment)."
      user:
        name: "{{ standard_user }}"
        comment: Standard user profile.
        shell: /bin/bash

    - name: "Test the standard user role."
      include_role:
        name: "standard_user"
