---
- name: Converge
  hosts: all
  vars_files: 
    - ../../management_user/defaults/main.yml
  tasks:
    - name: Update apt cache (on Debian)
      apt: 
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

    - name: Install dependencies
      pip:
        name: passlib
        state: present

    - name: "Test management user role"
      include_role:
        name: "management_user"
      vars:
        ansible_become_pass: "molecule_testing"
        ansible_ssh_pass: "molecule_testing"
        vault_management_pass: "molecule_testing"
