---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  vars_files: 
    - ../../management_user/defaults/main.yml
    - ../../standard_user/defaults/main.yml
  tasks:
  - name: "Check if {{ management_user }} exists"
    getent:
      database: passwd
      key: "{{ management_user }}"
    failed_when: getent_passwd is not defined

  - debug: var=getent_passwd

  - name: "Check to make sure the installed keys exist"
    stat:
      path: "/home/{{ standard_user }}/.ssh/{{ item }}"
    register: stat_result
    failed_when: stat_result is not defined
    with_fileglob:
      - ../../standard_user/files/*.pub
