---
name: Linting and Molecule Testing
'on':
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Lint the playbook and run Molecule tests before pushing to master.
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install molecule docker molecule-docker yamllint ansible-lint

      - name: Yamllint the directory.
        run: yamllint .

      # - name: Ansible-lint the directory.
      #   run: ansible-lint .
      
      # - name: Finally, run ansible-lint on every .yml file. 
      #   run: ansible-lint *.yml

      - name: Now, run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'