---
name: Linting only
'on':
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Lint the playbook before pushing to master.
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install yamllint ansible-lint

      - name: Verify the ansible-lint version.
        run: ansible-lint --version
 
      - name: Yamllint everything.
        run: yamllint .
      
      - name: Finally, run ansible-lint before merging to master. 
        run: ansible-lint .